name = "RAISDKResultsWrapper"
uuid = "b77b3abe-013f-4f9b-9096-7c0754454eb7"
authors = ["Nathan Daly <nhdaly@gmail.com> and contributors"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
RAI = "9c30249a-7e08-11ec-0e99-a323e937e79f"

[compat]
JSON3 = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
